### ISSUE TITLE
Does this search forward?

### ISSUE THREAD

**Issue by huyz** [rahulsenna/vscode-hippie-completion#1]
Maybe I'm confused, but this doesn't seem to search forward for me.  The `prev` only seems to backtrack but not actually look for words past the cursor.

This isn't how JetBrain's cyclic word expansion works.

**Comment by rahulsenna** [comment]
Sorry for the late reply, next searches from the cursor to the top of the file. prev should do exactly opposite for the cursor to the bottom of the file.

**Comment by rahulsenna** [comment]
"The prev only seems to backtrack but not actually look for words past the cursor." I see this point, I must have overlooked this since I don't really use this feature, thanks for reporting I'll try to correct this.

**Comment by rahulsenna** [comment]
I've fixed this issue in the latest commit. Thanks for reporting.
