### ISSUE TITLE
Swap "prev" and "next"

### ISSUE THREAD

**Issue by huyz** [rahulsenna/vscode-hippie-completion#2]
The prev and next seem to be reversed.
I can see that JetBrains calls "backward" what should be called forward, but I think that was a mistake.  Now with the current polarity, I'm forced to have the unfortunate inconsistently named bindings:
![screenshot 2022-11-19T171959Z](https://user-images.githubusercontent.com/128394/202863421-c2855bc0-b5b5-4dc3-bea1-9a117f1c9fee.png)

VS Code and Vim agree that "next" means looking forward past the cursor.

**Comment by rahulsenna** [comment]
I've answered this on your other query hope that helps.

**Comment by huyz** [comment]
Not sure that really answers it. This isn't a question as much as a request.  I'm suggesting that the plugin swap the meanings of "next" and "prev", to be consistent with VS Code and Vim (even if it's the opposite of JetBrains).  It is a VS Code extension after all :)

**Comment by rahulsenna** [comment]
I've just checked in Jetbrains IDE it works exactly like this, `Cyclic Expand Word (Backward)` searches from the cursor to the bottom of the file just like `hippie-completion.prev`

**Comment by huyz** [comment]
That's what I'm saying.  That JetBrains works like this, but I think they made the wrong decision, unlike VS Code and Vim.  it's intuitive for "Next" to mean "forward" and "Previous" to mean "backward", not the other way around, which is the way JetBrains has it.
I'm suggesting that you eschew JetBrains' terminology and instead go with the convention set by VS Code.  Just look at my screenshot again and you will see the inconsistency of "next" being assigned to `^P` where `P` stands for "previous".

**Comment by rahulsenna** [comment]
I believe you simply have a different preference. I do not think that Jetbrains made a wrong decision. Most people prefer the `tab completion` to work as it has been laid out, prioritizing word matches above the cursor because those are typically the most recently used words.

**Comment by huyz** [comment]
Ok, then "prev" means "next" and "next" means "prev". Got it :)
